<?php
$this->title = "My Albums";
$this->headTitle($this->title);
echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/index/index.css');
?>
<div class="layout-div gradient-gray" id="layout-header-div">
    <ul id="layout-navigation">
        <li data-href="<?php echo $this->baseUrl(); ?>/dashboard/index">Dashboard</li>
        <li data-href="<?php echo $this->baseUrl(); ?>/account/index">Konten</li>
        <li data-href="<?php echo $this->baseUrl(); ?>/buchungen">Buchungen</li>
        <li data-href="<?php echo $this->baseUrl(); ?>/einstellungen">Einstellungen</li>
    </ul>
</div>
<div class="layout-div" id="layout-loader-div"></div>
<div class="layout-div" id="layout-content-div">Start</div>
<div class="layout-div gradient-gray-inverse" id="layout-footer-div">Footer</div>
