<?php
$this->title = "My Albums";
$this->headTitle($this->title);
print($this->headLink()->prependStylesheet($this->baseUrl().'/styles/index/index.css'));
?>
<div class="layout-div gradient-gray" id="layout-header-div">
    <ul id="layout-navigation">
        <li data-href="<?php print($this->url(array('controller'=>'dashboard','action'=>'index'))); ?>">Dashboard</li>
        <li data-href="<?php print($this->url(array('controller'=>'account','action'=>'index'))); ?>">Konten</li>
        <li data-href="<?php print($this->url(array('controller'=>'booking','action'=>'index'))); ?>">Buchungen</li>
        <li data-href="<?php print($this->url(array('controller'=>'recurring-booking','action'=>'index'))); ?>">Wiederkehrende Buchungen</li>
        <li data-href="<?php print($this->url(array('controller'=>'period','action'=>'index'))); ?>">Zeiträume</li>
        <li data-href="<?php print($this->url(array('controller'=>'preferences','action'=>'index'))); ?>">Einstellungen</li>
    </ul>
</div>
<div class="layout-div" id="layout-loader-div"></div>
<div class="layout-div" id="layout-content-div">Start</div>
<div class="layout-div gradient-gray-inverse" id="layout-footer-div">Footer</div>
