<table>
<?php foreach($this->bookings as $booking) : ?>
    <tr>
        <td>
            <?php print($booking->description); ?>
        </td>
        <td>
            <?php print($booking->from_account_id); ?>
        </td>
        <td>
            <?php print($booking->to_account_id); ?>
        </td>
        <td>
            <?php print($booking->amount); ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>