<table>
<?php foreach($this->recurringBookings as $recurringBooking) : ?>
    <tr>
        <td>
            <?php print($recurringBooking->description); ?>
        </td>
        <td>
            <?php print($recurringBooking->from_account_id); ?>
        </td>
        <td>
            <?php print($recurringBooking->to_account_id); ?>
        </td>
        <td>
            <?php print($recurringBooking->amount); ?>
        </td>
        <td>
            <?php print($recurringBooking->start); ?>
        </td>
        <td>
            <?php print($recurringBooking->end); ?>
        </td>
        <td>
            <?php print($recurringBooking->period); ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>