<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

$this->headLink()->prependStylesheet($this->baseUrl() . '/styles/layout.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/styles/jquery-ui-1.8.22.custom.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery-1.7.2.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery-ui-1.8.22.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/layout.js');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>